CREATE TABLE "wrprc_status" (
	"jti" uuid PRIMARY KEY NOT NULL,
	"status_idx" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "wrprc_status_status_idx_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"revoked" boolean DEFAULT false NOT NULL,
	"revoked_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
